// SPDX-License-Identifier: MIT OR Unlicense
// Autogenerated using the Scaffold feature in wawa.Editors.
// Code generated by wawa.Editors is in public domain.
// Source: https://github.com/Emik03/wawa

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using Assets.Scripts.Missions;
using Assets.Scripts.Records;
using Assets.Scripts.Rules;
using Newtonsoft.Json;
using TMPro;
using UnityEngine;
using UnityEngine.Networking;
using static Assets.Scripts.Mods.ModInfo;

public sealed class InjectorNeedy : MonoBehaviour
{
    // Uncomment or remove as needed. Documentation for what each field does is as follows:
    // https://github.com/samfundev/KtaneTwitchPlays/wiki/External-Mod-Module-Support#additional-implementation-tasks

    /* [SerializeField]
    private bool
        TimeModeActive,
        TwitchShouldCancelCommand,
        TwitchPlaysActive,
        TwitchPlaysSkipTimeAllowed = true,
        ZenModeActive; */

    // [SerializeField]
    // private string TwitchHelpMessage, TwitchManualCode;

    /* [SerializeField]
    private List<KMBombModule> TwitchAbandonModule; */

    [SerializeField]
    private string _repoUrl;

    [SerializeField]
    private Transform _moduleAnchor;

    [SerializeField]
    private WireSeqComponent _wireSeq;

    private Animator _wireSeqAnimator;

    private static bool s_isFetchingRepo;

    private static bool s_hasFetchedRepo;

    private static KtaneModule[] s_repoData;

    private static event Action s_repoEvent;

    private static int s_lastModuleId;

    private KMNeedyModule _needy;

    private Selectable _selectable;

    private Selectable _dummySelectable;

    private int _moduleId;

    private bool _initActivate;

    private bool _initRepo;

    private BombComponent _nextComponent;

    private float _nextCountdownTime;

    private bool _isCountdownReady;

    private bool _isCountdownStarted;

    private bool _isNeedyActivated;

    private Coroutine _needyActivateRoutine;

    // private Coroutine _timerScrambleRoutine;

    private bool _isPreloading;

    private BombComponent _instantiatedComponent;

    private GameObject _componentPendingDestruction;

    private Selectable _instantiatedSelectable;

    private string _nestedTag;

    private NeedyTimer _needyTimer;

    private TextMeshPro _needyDisplayText;

    private InjectorModSettings _modConfig;

    private readonly List<string> _logQueue = new List<string>();

    private static readonly ComponentTypeEnum[] s_trivialVanillas = new[]
    {
        ComponentTypeEnum.Wires,
        ComponentTypeEnum.BigButton,
        ComponentTypeEnum.Keypad,
        ComponentTypeEnum.Simon,
        ComponentTypeEnum.WhosOnFirst,
        ComponentTypeEnum.Memory,
        ComponentTypeEnum.Morse,
        ComponentTypeEnum.Venn,
        ComponentTypeEnum.WireSequence,
        ComponentTypeEnum.Maze,
        ComponentTypeEnum.Password,
    };

    /* private static readonly string[] s_whitelistedDifficulties = new[]
    {
        "Trivial",
        "VeryEasy",
        "Easy",
        "Medium",
    }; */

    private static readonly string[] s_blacklistedMods = new string[]
    {
        "watchingPaintDry", // softlock
    };

    private void Log(string message) => Debug.Log($"[{_needy.ModuleDisplayName} #{_moduleId}] {message}");

    private void LogLower(string message) => Debug.Log($"<{_needy.ModuleDisplayName} #{_moduleId}> {message}");

    private void Awake()
    {
        _moduleId = ++s_lastModuleId;

        // it's such a shame that the Tweaks case gen doesn't respect this property (despite only ever being used by wire seq) since it just generates a quad for every backing instead of having dedicated models for shallow and deep backings
        GetComponent<BombComponent>().RequiresDeepBackingGeometry = true;
    }

    private void OnEnable()
    {
        Application.logMessageReceived += OnLogMessage;
    }

    private void OnDisable()
    {
        Application.logMessageReceived -= OnLogMessage;
    }

    private void Start()
    {
        _needy = GetComponent<KMNeedyModule>();
        _needy.OnActivate += OnActivate;
        _needy.OnNeedyActivation += OnNeedyActivation;
        _needy.OnNeedyDeactivation += OnNeedyDeactivation;
        _needy.OnTimerExpired += OnTimerExpired;

        _wireSeqAnimator = _wireSeq.GetComponent<Animator>();
        _wireSeq.OnPageLowerEnded += OnPageLowerEnded;

        _selectable = GetComponent<Selectable>();
        // i do this in a few mods: there's a "dummy" selectable in the root of the needy which is just there so things don't break when you select the needy and theres nothing inside of it to select
        _dummySelectable = _selectable.Children[0];

        // then we assign all of the basic selectable actions and map them so the submodule receives them (when present)
        // i think some of this is definitely borked in some way -julie, april 5th 2026
        _selectable.OnInteract += () => _instantiatedSelectable ? _instantiatedSelectable.HandleInteract() : true;
        _selectable.OnDeselect += sel => _instantiatedSelectable?.HandleDeselect(sel);
        _selectable.OnCancel += () => _instantiatedSelectable ? _instantiatedSelectable.HandleCancel() : true;
        _selectable.OnSelect += () => _instantiatedSelectable?.OnHighlight?.Invoke();
        _selectable.OnHighlight += () => _instantiatedSelectable?.OnHighlight?.Invoke();
        _selectable.OnHighlightEnded += () => _instantiatedSelectable?.OnHighlightEnded?.Invoke();
        _selectable.OnFocus += () => _instantiatedSelectable?.OnFocus?.Invoke();
        _selectable.OnDefocus += () => _instantiatedSelectable?.OnDefocus?.Invoke();
        _selectable.OnLeft += () => _instantiatedSelectable?.OnLeft?.Invoke();
        _selectable.OnRight += () => _instantiatedSelectable?.OnRight?.Invoke();

        _needyTimer = GetComponentInChildren<NeedyTimer>();
        _needyDisplayText = Instantiate(_needyTimer.Display.DisplayText, _needyTimer.Display.DisplayText.transform.parent);
        _needyTimer.Display.DisplayText.enabled = false;
        _needyDisplayText.enableAutoSizing = false;
        _needyDisplayText.fontSize = 17f;
        _needyDisplayText.margin = new Vector4(0f, 0.34f, 0f, 0f);

        // _modConfig = new Config<InjectorModSettings>().Read();
        _modConfig = new ModConfig<InjectorModSettings>("InjectorSettings").Read();

        if (_modConfig.HasWhitelist)
            Log($"WHITELIST SETTING IS ENABLED! Whitelisted modules: {_modConfig.WhitelistModIds.Join(", ")}");

        ReplaceButtonRules();

        WaitForRepo();
    }

    private void ReplaceButtonRules()
    {
        var ruleSet = RuleManager.Instance.ButtonRuleSet;
        foreach (var rule in ruleSet.HoldRuleList)
        {
            if (rule.Solution.Name.StartsWith("ButtonRelease"))
            {
                LogLower($"Replacing solution {rule.Solution.Name} for rule: {rule}");
                string digit = rule.Solution.Name.Replace("ButtonRelease", "");
                rule.Solution = new Solution
                {
                    Name = $"InjectorNeedy_ButtonRelease{digit}",
                    Text = $"release when the countdown timer has a {digit} in any position.",
                    SolutionMethod = (component, args) => GetButtonFormattedTime(component).Contains(digit) ? 0 : 1,
                };
            }
            else if (rule.Solution.Name.StartsWith("BombTimerModifier_ButtonRelease"))
            {
                LogLower($"Replacing BombTimerModifier solution {rule.Solution.Name} for rule: {rule}");
                var btmSolutionMethod = rule.Solution.SolutionMethod;
                string digit = rule.Solution.Name.Replace("ButtonRelease", "");
                rule.Solution = new Solution
                {
                    Name = $"InjectorNeedy_ButtonRelease{digit}",
                    Text = $"release when the countdown timer has a {digit} in any position.",
                    SolutionMethod = (component, args) => component.GetComponentInParent<InjectorNeedy>() ? GetButtonFormattedTime(component).Contains(digit) ? 0 : 1 : btmSolutionMethod(component, args),
                };
            }
        }
    }

    private static string GetButtonFormattedTime(BombComponent component)
    {
        var needy = component.GetComponentInParent<InjectorNeedy>();
        if (needy)
            return needy.GetBombInfoFormattedTime();

        return component.Bomb.GetTimer().text.text;
    }

    private void Update()
    {
        UpdateDisplay();
    }

    private void UpdateDisplay()
    {
        if (_needyTimer.isRunning && _isCountdownReady)
        {
            _needyDisplayText.text = GetBombInfoFormattedTime();
        }
        else
        {
            _needyDisplayText.text = "";
        }
    }

    private void OnFetchComplete(string raw, string source)
    {
        var res = JsonConvert.DeserializeObject<KtaneResponse>(raw);
        s_repoData = res.Modules;
        s_hasFetchedRepo = true;
        s_isFetchingRepo = false;
        s_repoEvent?.Invoke();
        Log($"Loaded data (Modules: {s_repoData.Length}, Source: {source})");
        LogLower($"Pool of mods to choose from: {s_repoData.Where(RepoFilter).Select(m => $"{m.Name} ({m.ModuleId})").Join(", ")}");
    }

    private IEnumerator DoFetchRepo()
    {
        if (s_isFetchingRepo)
            yield break;

        s_isFetchingRepo = true;

        // if present, we use the tweaks backup! unless it's over a week old. then we don't want it.

        var backupPath = Path.Combine(Application.persistentDataPath, "RepositoryBackup.json");
        if (File.Exists(backupPath) && File.GetLastWriteTime(backupPath) > DateTime.Now.AddDays(-7))
        {
            try
            {
                OnFetchComplete(File.ReadAllText(backupPath, Encoding.UTF8), "TweaksBackup");
                yield break;
            }
            catch (Exception e)
            {
                Log($"Failed to load Tweaks repository backup: {e}");
            }
        }

        using (var req = UnityWebRequest.Get(_repoUrl))
        {
            yield return req.SendWebRequest();

            if (req.isHttpError || req.isNetworkError)
            {
                Log($"Failed to load repository data from {_repoUrl}: [{req.responseCode}] {req.error}");
            }
            else
            {
                OnFetchComplete(req.downloadHandler.text, "Fetch");
            }
        }
    }

    private void WaitForRepo()
    {
        if (s_hasFetchedRepo)
        {
            OnRepoFetched();
            return;
        }

        if (!s_hasFetchedRepo || s_isFetchingRepo)
            s_repoEvent += OnRepoFetched;

        if (!s_hasFetchedRepo && !s_isFetchingRepo)
            StartCoroutine(DoFetchRepo());
    }

    private static bool IsFakeModule(BombComponent component)
    {
        // tweaks conveniently adds a ModSource to fake modules (in alignment with real module standards) and puts its own name in the field. so that's helpful
        var source = component.GetComponent<ModSource>();
        return source && source.ModName == "Tweaks";
    }

    private bool SetNextComponent(BombComponent component, float countdownTime = -1f)
    {
        // a series of final checks to ensure the component meets at least the most critical requirements

        if (!component)
        {
            Log("Failed to set next component: null");
            return false;
        }

        if (!component.IsSolvable)
        {
            Log($"Failed to set next component: {component} is not solvable!");
            return false;
        }

        if (IsFakeModule(component))
        {
            Log($"Failed to set next component: {component} is a Tweaks proxy module!");
            return false;
        }

        // then we assign the nextcomponent field

        _isPreloading = false;
        _nextComponent = component;
        _nextCountdownTime = countdownTime > 0f ? countdownTime : _needy.CountdownTime;

        // and the rest of this is just getting the mod id in order to log it

        string name = _nextComponent.ComponentType.ToString();
        var modComponent = _nextComponent.GetComponent<ModBombComponent>();
        if (modComponent)
            name = modComponent.GetModComponentType();

        LogLower($"Set next component: {name} ({_nextComponent.GetModuleDisplayName()})");

        return true;
    }

    private bool RepoFilter(KtaneModule mod)
    {
        if (!string.IsNullOrEmpty(mod.TranslationOf)) return false;
        if (mod.Type != "Regular") return false;
        if (mod.Origin != "Mods") return false;
        if (s_blacklistedMods.Contains(mod.ModuleId)) return false;
        if (_modConfig.HasWhitelist && !_modConfig.WhitelistModIds.Contains(mod.ModuleId)) return false;
        // if (!s_whitelistedDifficulties.Contains(mod.DefuserDifficulty)) return false;
        // if (!s_whitelistedDifficulties.Contains(mod.ExpertDifficulty)) return false;
        // if (!((mod.TwitchPlays != null && mod.TwitchPlays.Score <= 5) || (mod.DefuserDifficulty == "Trivial" && mod.ExpertDifficulty == "Trivial"))) return false;
        if (mod.TwitchPlays == null) return false;
        if (mod.TwitchPlays.Score > 5) return false;
        // boss condition feels unnecessary with the quirks condition, though as of writing this there are 2 modules that have a boss status but no quirks (however one is a needy and one has a TP score of 9 so they're irrelevant regardless) but nevertheless i will just leave this condition here just to be safe
        if (mod.BossStatus == "FullBoss" || mod.BossStatus == "SemiBoss") return false;
        if (!string.IsNullOrEmpty(mod.Quirks)) return false;
        return true;
    }

    private void Preload() => StartCoroutine(PreloadMod());

    // okay 4:00 am julie here. this is the main mod loading code. most of it is really truly just DBML stuff. without DBML this would be so much simpler.
    private IEnumerator PreloadMod()
    {
        // prevent double preload
        if (_isPreloading)
            yield break;

        LogLower("Preloading...");

        _isPreloading = true;
        _nextComponent = null;
        _nextCountdownTime = _needy.CountdownTime;

        // display the tester module if it is currently bundled
        if (ModManager.Instance.loadedBombComponents.ContainsKey("InjectorTester") && SetNextComponent(ModManager.Instance.loadedBombComponents["InjectorTester"]))
            yield break;

        if (s_repoData != null)
        {
            // loadedBombComponents INCLUDES unloaded dbml modules btw. tweaks just sticks a bunch of fake modules in there to trick the game
            var loaded = ModManager.Instance.loadedBombComponents;

            // a list of "applicable" mods that are also loaded
            var overlap = s_repoData.Where(RepoFilter).Where(m => loaded.ContainsKey(m.ModuleId));

            if (overlap.Any())
            {
                var repoMod = overlap.PickRandom();
                LogLower($"Selected {repoMod.ModuleId} ({repoMod.Name})");

                var timeCandidate = repoMod.TwitchPlays != null ? 45f + (float)repoMod.TwitchPlays.Score * 15f : _needy.CountdownTime;

                var loadedComponent = loaded[repoMod.ModuleId];
                if (IsFakeModule(loadedComponent))
                {
                    LogLower($"{repoMod.ModuleId} is a proxy Tweaks module, loading real module...");
                    if (repoMod.SteamId == null)
                    {
                        LogLower($"{repoMod.ModuleId} has no Steam ID! Unable to load.");
                    }
                    else
                    {
                        // so this is basically just what Tweaks does for dbml but a little simpler

                        var workshopPath = ReflectionHelper.FindType("Utilities", "TweaksAssembly")
                            .GetValue<string>("SteamWorkshopDirectory");

                        var modPath = Path.Combine(workshopPath, repoMod.SteamId);
                        LogLower($"Loading mod at {modPath}");

                        // LoadMod = load the mod info json, plus the mod settings and assemblies if the mod info json loads successfully
                        var mod = Mod.LoadMod(modPath, ModSourceEnum.Local);

                        if (mod == null)
                        {
                            Log($"Failed to load mod at {modPath}");
                        }
                        else
                        {
                            yield return StartCoroutine(ModManager.Instance.LoadModAssetBundles(mod));

                            mod.RemoveMissions();
                            mod.RemoveSoundOverrides();

                            foreach (var service in mod.GetModObjects<ModService>())
                            {
                                var serviceObj = Instantiate(service.gameObject);
                                serviceObj.transform.parent = ModManager.Instance.transform;
                                mod.AddServiceObject(serviceObj);
                            }

                            // i genuinely have NO IDEA why tweaks doesn't add loaded bomb components to loadedBombComponents. because it's skipping the part of the game code that does it. and then doesn't do it itself. because then like EVERY TIME you load a module that you ALREADY loaded before with DBML it STILL HAS TO GO THROUGH DBML so it'll say "loading X mods" for like a frame or two while it checks its OWN LIST OF MODS instead of just letting the game natively find it! i just dont understand it!!!! but I AM adding loaded bomb components to loadedBombComponents (see below) because that makes sense and it works wonderfully!!

                            foreach (var module in mod.GetModObjects<KMBombModule>())
                                loaded[module.ModuleType] = module.GetComponent<BombComponent>();

                            foreach (var module in mod.GetModObjects<KMNeedyModule>())
                                loaded[module.ModuleType] = module.GetComponent<BombComponent>();

                            ModManager.Instance.loadedMods[modPath] = mod;

                            if (loaded.ContainsKey(repoMod.ModuleId))
                            {
                                var newLoadedComponent = loaded[repoMod.ModuleId];
                                // set component
                                if (SetNextComponent(newLoadedComponent, timeCandidate))
                                    yield break;
                            }
                            else
                            {
                                // akin to Tweaks' "unable to load the module for [module id] ([steam id])"
                                Log($"Mod {mod.ModID} does NOT contain module {repoMod.ModuleId}! (after loading through DBML!) what is this witchcraft!");
                            }
                        }
                    }
                }
                else
                {
                    // set component
                    if (SetNextComponent(loadedComponent, timeCandidate))
                        yield break;
                }
            }
        }

        Log("Unable to load any modded modules. Falling back to vanilla modules.");

        var compType = s_trivialVanillas.PickRandom();
        Log($"Selected vanilla module: {compType}");

        var prefab = Prefabs.Instance.BombGenerator.componentPrefabs.FirstOrDefault(comp => comp.ComponentType == compType);
        // set component
        if (SetNextComponent(prefab))
            yield break;

        _isPreloading = false;
        Log("Unable to load vanilla fallback. (this should NEVER happen! please report this to the mod author!)");
    }

    private void OnActivate()
    {
        if (_initActivate)
            return;

        _initActivate = true;
        CheckInit();
    }

    private void OnRepoFetched()
    {
        if (_initRepo)
            return;

        _initRepo = true;
        CheckInit();
    }

    private void CheckInit()
    {
        // simple counter system; we want to start preloading once (a) the module is activated and (b) the repo data is loaded. so as soon as both actions are completed, this will be true
        if (_initActivate && _initRepo)
        {
            Preload();
        }
    }

    private void OnNeedyActivation()
    {
        // we do NOT want to double activate - disasterous with the whole instantiating modules thing - so we keep track of a boolean to prevent that
        if (!_isNeedyActivated)
        {
            _isNeedyActivated = true;
            _needyActivateRoutine = StartCoroutine(HandleNeedyActivation());
            // _timerScrambleRoutine = StartCoroutine(TimerScramble());
        }
    }

    private static bool TryGetModuleId(Component mod, out int id)
    {
        foreach (var comp in mod.GetComponents<Component>())
        {
            if (!comp)
                continue;

            var res = new Dictionary<string, int>();

            // this concept is pulled from Tweaks but just kinda simplified. it doesn't have to be perfect, it's just helpful for better logging

            var type = comp.GetType();
            var flags = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance;

            foreach (var field in type.GetAllFields(flags))
                if (field.FieldType == typeof(int))
                    res[field.Name] = (int)field.GetValue(comp);

            foreach (var prop in type.GetAllProperties(flags))
                if (prop.PropertyType == typeof(int))
                    res[prop.Name] = (int)prop.GetValue(comp, null);

            foreach (var pair in res)
                if (Regex.IsMatch(pair.Key, "(mod|log).*(id|num)", RegexOptions.IgnoreCase))
                {
                    id = pair.Value;
                    return true;
                }
        }

        id = 0;
        return false;
    }

    private string GetLoggingTag()
    {
        if (_instantiatedComponent)
        {
            // should never be needy but just in case
            if (_instantiatedComponent.ComponentType == ComponentTypeEnum.Mod || _instantiatedComponent.ComponentType == ComponentTypeEnum.NeedyMod)
            {
                int id;
                if (TryGetModuleId(_instantiatedComponent, out id))
                {
                    return $"{_instantiatedComponent.GetModuleDisplayName()} #{id}";
                }
            }
            else
            {
                // vanilla modules have a proper log4net logger so we can just pull the logger name (with the id and everything) directly
                return _instantiatedComponent.logger.Logger.Name;
            }
        }

        return null;
    }

    private void TryMatchLog(string message)
    {
        if (_nestedTag != null && _instantiatedComponent)
        {
            string fullTag = $"[{_nestedTag}] ";
            if (message != null && message.StartsWith(fullTag))
            {
                var body = message.Substring(fullTag.Length);
                Log($"[{_instantiatedComponent.GetModuleDisplayName()}] {body}");
            }
        }
    }

    private void OnLogMessage(string logString, string stackTrace, LogType type)
    {
        // when something gets logged:

        // we add it to the log queue in case we determine the logging id later down the line and need to pull older logs with that tag to display them in LFA
        _logQueue.Add(logString);

        // and we also see if it matches the active logging tag, when applicable
        TryMatchLog(logString);
    }

    /* private IEnumerator TimerScramble()
    {
        int lastTime = 0;
        while (true)
        {
            int time;
            do time = Random.Range(1, 98);
            while (time == lastTime);
            lastTime = time;
            // WHY DOES THE IN-GAME NEEDY TIMER *ROUND* THE TIME FOR THE DISPLAY INSTEAD OF FLOOR OR CEILING OR LITERALLY ANYTHING LOGICAL
            _needy.SetNeedyTimeRemaining(time);
            yield return new WaitForSeconds(0.25f);
            _needy.SetNeedyTimeRemaining(time);
            yield return new WaitForSeconds(0.25f);
            // float started = Time.time;
            // while ((Time.time - started) < 0.5f)
            // {
            //     _needy.SetNeedyTimeRemaining(time);
            //     yield return null;
            // }
            // yield return new WaitForSeconds(0.5f);
        }
    } */

    private IEnumerator HandleNeedyActivation()
    {
        _isCountdownStarted = false;
        _isCountdownReady = false;

        if (_isPreloading)
        {
            LogLower("Attempted to activate needy but module is still preloading. Waiting...");
            float waitTime = 0f;
            while (_isPreloading)
            {
                if (waitTime >= 10f)
                {
                    Log("Waited 10 seconds for preload with no result. Deactivating.");
                    _needy.HandlePass();
                    yield break;
                }

                // keep the timer at its initial value until we're ready
                _needy.SetNeedyTimeRemaining(_needy.CountdownTime);

                waitTime += Time.deltaTime;
            }
            // yield return new WaitUntil(() => !_isPreloading);
        }

        // this would probably happen if preload failed which could possibly happen if the repo data fails to load, for instance
        if (!_nextComponent)
        {
            Log("Attempted to activate needy but no module is available! (this should never happen)");
            _needy.HandlePass();
            yield break;
        }

        _needy.SetNeedyTimeRemaining(_nextCountdownTime);
        _isCountdownReady = true;
        UpdateDisplay();

        Log($"Instantiating {_nextComponent.GetModuleDisplayName()} ({_nextComponent.name})");

        _logQueue.Clear();

        // if there's still somehow a component here, get rid of it!!
        // DeactivateComponent(true);

        // destroy previous component if it still exists (a replacement for the old DeactivateComponent(true) invocation)
        OnPageLowerEnded();

        var bombInfos = _nextComponent.GetComponentsInChildren<KMBombInfo>(true);
        foreach (var bombInfo in bombInfos)
        {
            if (!bombInfo.GetComponent<InjectorBombInfo>())
            {
                LogLower($"Replacing bomb info for {bombInfo}");

                var defaultBombInfo = bombInfo.GetComponent<ModBombInfo>();
                if (defaultBombInfo)
                    DestroyImmediate(defaultBombInfo);

                bombInfo.gameObject.AddComponent<InjectorBombInfo>();
            }
        }

        _nextComponent.transform.localScale = Vector3.one / _moduleAnchor.lossyScale.x;

        // spawn the mod on the thing
        var component = Instantiate(_nextComponent, _moduleAnchor);
        _instantiatedComponent = component;

        _nextComponent.transform.localScale = Vector3.one;

        // make sure the mod's dimensions are all squared away with the transform of the anchor
        component.transform.localPosition = Vector3.zero;
        component.transform.localRotation = Quaternion.identity;
        component.transform.localScale = Vector3.one;

        // handle these basic events and tell it what bomb to reference
        component.OnPass += OnNestedPass;
        component.OnStrike += OnNestedStrike;
        component.Bomb = GetComponentInParent<Bomb>();

        _instantiatedSelectable = component.GetComponent<Selectable>();

        // var currentSelectable = KTInputManager.Instance.GetCurrentSelectable();

        bool shouldCancel = KTInputManager.Instance.SelectableManager.CurrentParent == _selectable || KTInputManager.Instance.SelectableManager.CurrentParent == _dummySelectable;

        _selectable.DeactivateImmediateChildSelectableAreas();

        _selectable.Children[0] = _instantiatedSelectable;
        _instantiatedSelectable.Parent = _selectable;
        _instantiatedSelectable.IsPassThrough = true;
        _selectable.Init();

        if (KTInputManager.Instance.IsMotionControlMode())
            _selectable.ActivateMotionControls();

        foreach (var occluder in component.GetComponentsInChildren<CrosshairOccluder>())
        {
            // vanillas have a lot of "crosshair occluders" which are fun but they mess things up when we're trying to access the needy from the outside. so we'll just disable those
            var collider = occluder.GetComponent<Collider>();
            if (collider)
                collider.enabled = false;
        }

        // i acknowledge this may not apply to any selectables that get generated later but this should work enough for our purposes
        foreach (var selectable in component.GetComponentsInChildren<KMSelectable>(true))
        {
            // overwrite AddInteractionPunch for all submodule selectables in order to lessen the intensity (by multiplying by how much we are scaling down the module)
            selectable.OnInteractionPunch = intensity => KTInputManager.Instance.AddInteractionPunch(selectable.transform.position, Assets.Scripts.Input.AbstractHapticUtil.HapticType.Interaction, intensity * 0.412905157f, 0.75f, 0.3f);
        }

        // if (currentSelectable && currentSelectable.Parent == _selectable)
        if (shouldCancel)
        {
            StartCoroutine(CancelRoutine());
        }

        yield return null;

        component.Activate();
        LogLower("Component activated");

        _wireSeqAnimator.SetBool("Lower", false);
        GetComponent<KMAudio>().PlayGameSoundAtTransform(KMSoundOverride.SoundEffect.WireSequenceMechanism, _wireSeq.transform);

        _nestedTag = GetLoggingTag();
        LogLower(_nestedTag == null ? $"Failed to detect logging tag for {_nextComponent.name}" : $"Detected logging tag for {_nextComponent.name}: {_nestedTag}");

        foreach (var entry in new List<string>(_logQueue))
        {
            TryMatchLog(entry);
        }

        _logQueue.Clear();

        // hold the timer at its initial value for 2s, to simulate how the bomb timer works
        float elapsed = 0f;
        while (elapsed < 2f)
        {
            _needy.SetNeedyTimeRemaining(_nextCountdownTime);
            elapsed += Time.deltaTime;
            yield return null;
        }

        _isCountdownStarted = true;
    }

    private bool OnNestedPass(BombComponent component)
    {
        if (_isNeedyActivated)
        {
            // LogLower("Received pass from component");
            Log("Solved!");
            _needy.HandlePass();

            // deactivate internally
            _isNeedyActivated = false;
            DeactivateComponent();
            Preload();
            // OnTimerExpired();
        }
        else
        {
            LogLower("Received pass from component (ignoring)");
        }
        return false;
    }

    private bool OnNestedStrike(BombComponent component)
    {
        var record = RecordManager.Instance.currentRecord;
        if (record != null)
        {
            // roll back the strike index so we can overwrite the nested module's strike with our needy strike
            // even if we're "ignoring" the strike below and not issuing a new one, we still want to roll this back so that the submod strike has no effect on the bomb
            record.currentStrikeIndex--;

            // also erase that strike record in case we happen to be ignoring the strike below
            record.Strikes[record.currentStrikeIndex] = null;
        }

        if (_isNeedyActivated)
        {
            // LogLower("Received strike from component");
            Log("Strike!");

            // strike the needy module
            _needy.HandleStrike();

            // deactivate the needy module as well
            _needy.HandlePass();

            // deactivate internally
            _isNeedyActivated = false;
            DeactivateComponent();
            Preload();
        }
        else
        {
            LogLower("Received strike from component (ignoring)");
        }
        return false;
    }

    private IEnumerator CancelRoutine()
    {
        KTInputManager.Instance.Select(_selectable.Parent);
        KTInputManager.Instance.SelectableManager.HandleInteract();
        yield return null;
        KTInputManager.Instance.Select(_selectable);
        KTInputManager.Instance.SelectableManager.HandleInteract();
    }

    private void DeactivateComponent()
    {
        if (_needyActivateRoutine != null)
            StopCoroutine(_needyActivateRoutine);

        // if (_timerScrambleRoutine != null)
        //     StopCoroutine(_timerScrambleRoutine);

        if (_instantiatedComponent)
        {
            // var currentSelectable = KTInputManager.Instance.GetCurrentSelectable();

            // bool shouldCancel = currentSelectable.Parent == _selectable.Children[0];
            bool shouldCancel = KTInputManager.Instance.SelectableManager.CurrentParent == _selectable || KTInputManager.Instance.SelectableManager.CurrentParent == _dummySelectable;

            // if (shouldCancel)
            //     KTInputManager.Instance.HandleCancel();

            _selectable.Children[0] = _dummySelectable;
            _selectable.Init();

            if (shouldCancel)
            {
                StartCoroutine(CancelRoutine());
            }

            /* if (currentSelectable && (currentSelectable.Parent == _selectable || (currentSelectable.Parent && currentSelectable.Parent.Parent == _selectable)))
                _selectable.OnDrillTo(); */

            /* if (currentSelectable && currentSelectable.Parent == _selectable)
            {
                _selectable.OnDrillTo();
                currentSelectable.SetHighlight(false);
                KTInputManager.Instance.Select(_dummySelectable);
            } */

            if (KTInputManager.Instance.IsMotionControlMode())
                _selectable.ActivateMotionControls();

            // KTInputManager.Instance.SelectableManager.Select(_dummySelectable, false);

            // remove these events! the module doesn't stop listening for these when it's destroyed so it throws exceptions :(
            var holdable = _instantiatedComponent.Bomb.GetComponent<FloatingHoldable>();
            if (holdable)
            {
                holdable.OnLetGo -= _instantiatedComponent.OnBombLetGo;
                holdable.OnFocusChild -= _instantiatedComponent.OnBombChildFocused;
                holdable.OnFocusChildComplete -= _instantiatedComponent.OnBombChildFocusedComplete;
            }

            // assign this so we can destroy it once the wire seq mechanism hits the bottom
            _componentPendingDestruction = _instantiatedComponent.gameObject;

            _instantiatedComponent = null;
            _instantiatedSelectable = null;

            // if (immediate)
            // {
            //     OnPageLowerEnded();
            // }
            // else
            // {
            _wireSeqAnimator.SetBool("Lower", true);
            GetComponent<KMAudio>().PlayGameSoundAtTransform(KMSoundOverride.SoundEffect.WireSequenceMechanism, _wireSeq.transform);
            // }
        }
    }

    private void OnPageLowerEnded()
    {
        if (_componentPendingDestruction)
        {
            Destroy(_componentPendingDestruction);
            _componentPendingDestruction = null; // just in case
        }
    }

    // if force-deactivated by the game
    private void OnNeedyDeactivation()
    {
        if (_isNeedyActivated)
        {
            _isNeedyActivated = false;
            DeactivateComponent();
        }
    }

    private void OnTimerExpired()
    {
        if (_isNeedyActivated)
        {
            Log("Strike! (time expired)");

            _needy.HandleStrike();
            _needy.HandlePass();

            _isNeedyActivated = false;
            DeactivateComponent();

            Preload();
        }
    }

    internal float GetBombInfoTime() => _needyTimer.isRunning ? _isCountdownStarted ? _needyTimer.TimeRemaining : _nextCountdownTime : 0f;

    internal string GetBombInfoFormattedTime()
    {
        float seconds = GetBombInfoTime();
        float clampedSeconds = seconds < 0f ? 0f : seconds;

        int totalMinutes = (int)(clampedSeconds / 60);
        int totalSeconds = (int)(clampedSeconds % 60);
        int totalMilliseconds = (int)(clampedSeconds * 10 % 10);

        if (clampedSeconds < 60)
            return string.Format("{0:D2}.{1}", totalSeconds, totalMilliseconds);

        return string.Format("{0}:{1:D2}", totalMinutes, totalSeconds);
    }

    internal int GetBombInfoStrikes()
    {
        return GetComponentInParent<Bomb>().NumStrikes;
    }

    private List<string> GetSubmoduleNameList()
    {
        if (_instantiatedComponent)
            return new List<string> { _instantiatedComponent.GetModuleDisplayName() };

        return new List<string>();
    }

    private List<string> GetSubmoduleIDList()
    {
        if (_instantiatedComponent)
        {
            string id = _instantiatedComponent.ComponentType.ToString();
            var modComponent = _instantiatedComponent.GetComponent<ModBombComponent>();
            if (modComponent)
                id = modComponent.GetModComponentType();

            return new List<string> { id };
        }

        return new List<string>();
    }

    internal List<string> GetBombInfoModuleNames() => GetSubmoduleNameList();

    internal List<string> GetBombInfoSolvableModuleNames() => GetSubmoduleNameList();

    internal List<string> GetBombInfoSolvedModuleNames() => new List<string>();

    internal List<string> GetBombInfoModuleIDs() => GetSubmoduleIDList();

    internal List<string> GetBombInfoSolvableModuleIDs() => GetSubmoduleIDList();

    internal List<string> GetBombInfoSolvedModuleIDs() => new List<string>();

    // throwing TP out the window. just not happening rn. maybe someday

    /* private IEnumerator ProcessTwitchCommand(string command)
    {
        throw new NotImplementedException();
    }

    private IEnumerator TwitchHandleForcedSolve()
    {
        throw new NotImplementedException();
    } */
}
