// SPDX-License-Identifier: MIT OR Unlicense
// Autogenerated using the Scaffold feature in wawa.Editors.
// Code generated by wawa.Editors is in public domain.
// Source: https://github.com/Emik03/wawa

using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Random = UnityEngine.Random;

/// <summary>On the Subject of <see cref="InjectorTester"/>.</summary>
public sealed class InjectorTester : MonoBehaviour
{
    // Uncomment or remove as needed. Documentation for what each field does is as follows:
    // https://github.com/samfundev/KtaneTwitchPlays/wiki/External-Mod-Module-Support#additional-implementation-tasks

    /* [SerializeField]
    bool
        TimeModeActive,
        TwitchShouldCancelCommand,
        TwitchPlaysActive,
        TwitchPlaysSkipTimeAllowed = true,
        ZenModeActive;

    [SerializeField]
    string TwitchHelpMessage, TwitchManualCode;

    [SerializeField]
    List<KMBombModule> TwitchAbandonModule; */

    [SerializeField]
    KMBombModule _solvable;

    [SerializeField]
    private TextMesh _text;

    static int s_lastModuleId;

    int _moduleId;

    void Log(string message, params object[] args)
    {
        var log = string.Format(message, args);
        Debug.LogFormat("[{0} #{1}] {2}", _solvable.ModuleDisplayName, _moduleId, log);
    }

    private void Awake()
    {
        _moduleId = ++s_lastModuleId;
        Log($"Awake Debug:\n{GetDebugText()}");
    }

    void Start()
    {
        _solvable.OnActivate += OnActivate;
        Log($"Start Debug:\n{GetDebugText()}");
    }

    private string GetDebugText()
    {
        var info = GetComponent<KMBombInfo>();
        return new[]
        {
            $"Time: {info.GetTime()}",
            $"Formatted time: {info.GetFormattedTime()}",
            $"Strikes: {info.GetStrikes()}",
            $"Names: {info.GetModuleNames().Join(", ")}",
            $"IDs: {info.GetModuleIDs().Join(", ")}",
        }.Join("\n");
    }

    private void Update()
    {
        _text.text = GetDebugText();
    }

    void OnActivate()
    {
        Log($"Activate Debug:\n{GetDebugText()}");
    }

    /* IEnumerator ProcessTwitchCommand(string command)
    {
        throw new NotImplementedException();
    }

    IEnumerator TwitchHandleForcedSolve()
    {
        throw new NotImplementedException();
    } */
}
